#!/bin/sh

echo "************Test Case 1*************"
./grep240 'a*r' < ~cs240ta/win2003/grep/months.txt

echo "************Test Case 2*************"
./grep240 -i 'a*r' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 3*************"
./grep240 -i 'E*r' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 4*************"
./grep240 E ~cs240ta/win2003/grep/months.txt

echo "************Test Case 5*************"
./grep240 -i E < ~cs240ta/win2003/grep/months.txt

echo "************Test Case 6*************"
./grep240 -i '*' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 7*************"
./grep240 -i '\*' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 8*************"
./grep240 -i '\\\*' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 9*************"
./grep240 -i '\*\*' < ~cs240ta/win2003/grep/months.txt

echo "************Test Case 10************"
./grep240 '\\\\\\' ~cs240ta/win2003/grep/months.txt

echo "************Test Case 11************"
./grep240 '\\*\\' < ~cs240ta/win2003/grep/months.txt

echo "DONE"
